version: "3.3"

services:
  test-app:
    build: .
    image: "wallet-app:latest"
    container_name: container-app
    environment:
      - DB_PASSWORD=password
      - DB_USERNAME=user
      - DB_URL=jdbc:postgresql://db:5432/walletdb
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: container-db
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '64689:5432'
    restart: always